version: "3.8"
services:
  frontend_app:
    container_name: frontend_app
    image: node:21
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    tty: true
    hostname: frontend
    working_dir: /app
    networks:
      - supabase_network
    env_file:
      - ./env/local.docker.env
      - ./env/secrets.env
    entrypoint: "/bin/bash -c 'yarn set version 4.1.0 && yarn install --refresh-lockfile && yarn web'"
  storybook:
    container_name: storybook
    image: node:21
    ports:
      - 6006:6006
    volumes:
      - ./frontend:/app
    tty: true
    hostname: storybook
    working_dir: /app
    networks:
      - supabase_network
    env_file:
      - ./env/local.docker.env
      - ./env/secrets.env
    entrypoint: "/bin/bash -c 'yarn set version 4.1.0 && yarn install --refresh-lockfile && yarn storybook'"

networks:
  supabase_network:
    name: supabase_network_${PROJECT_NAME}
    external: true
